# Generated by Django 3.2.7 on 2021-09-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('fname', models.CharField(max_length=150, verbose_name='Имя')),
                ('sname', models.CharField(blank=True, max_length=150, verbose_name='Отчеств')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizardapp.person', verbose_name='Посетитель')),
            ],
        ),
    ]
